addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - hugo
      - python-pygments

install:
  - rm -rf public || exit 0

script:
  - hugo

# https://docs.travis-ci.com/user/deployment/pages/
deploy:
  provider: pages
  project-name: mysupertest
  skip-cleanup: true
  #committer-from-gh: false
  name: $GITHUB_USERNAME
  email: $GITHUB_EMAIL
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  verbose: true
  keep-history: true
  local-dir: public
  fqdn: example.com
  target-branch: gh-pages
  on:
    branch: master
